name: spotify_mockup
description: A Spotify mockup made in flutter.

version: 1.0.0

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  google_fonts: ^0.4.3
  outline_material_icons: ^0.1.1
  palette_generator: ^0.2.2
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true